parameters:
#    vdg_aulas_mentor_alimentos.example.class: VDG\AulasMentor\AlimentosBundle\Example

services:
#    vdg_aulas_mentor_alimentos.example:
#        class: %vdg_aulas_mentor_alimentos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
