parameters:
#    vdg_aulas_mentor_ejercicio.example.class: VDG\AulasMentor\EjercicioBundle\Example

services:
#    vdg_aulas_mentor_ejercicio.example:
#        class: %vdg_aulas_mentor_ejercicio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
